services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: Development
    restart: always
    ports:
      - 5173:5173
    tty: true
    stdin_open: true
    networks:
      - app_network
    volumes:
      - ./apps/client:/app/apps/client
      - client_data:/app/apps/client/node_modules
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: Development
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - app_network
    volumes:
      - ./apps/server:/app/apps/server
      - server_data:/app/apps/server/node_modules

networks:
  app_network:
    driver: bridge

volumes:
  client_data:
  server_data:
