services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-prodcution}
      target: ${NODE_ENV:-prodcution}
    environment:
      - NODE_ENV=${NODE_ENV:-prodcution}
    ports:
      - 80:80
    networks:
      - app_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-prodcution}
      target: ${NODE_ENV:-prodcution}
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-prodcution}
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
