packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - workerd

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - lefthook
  - prisma
  - sharp
