services:
  app:
    container_name: fullstack-portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION-22.04}
    env_file:
      - devcontainer.env
      - ../.env
    volumes:
      - ../.:/workspace:cached
    hostname: fullstack-portfolio-app
    networks:
      - app_network
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    command: >
      postgres
      -c timezone=${PG_TZ-Asia/Tokyo}
      -c log_timezone=${PG_TZ-Asia/Tokyo}
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER-dev} -d ${POSTGRES_DB-portfolio_dev} -q"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
